--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: wpapp-deploy 
  labels: 
    app: wp 
    name: wpapp-deploy 
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: wp
      name: wpapp-po
  template:
    metadata:
      name: wpapp-po 
      labels:
        app: wp
        name: wpapp-po 
    spec:
      containers:
      - name: wpapp-container
        image: wordpress:5 
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: wpapp-cm
        - secretRef:
            name: wpapp-secret
        ports:
        - containerPort: 80

---
apiVersion: v1 
kind: Service
metadata:
  name: wpapp-svc 
  labels: 
    app: wp
    name: wpapp-svc
spec:
  type: ClusterIP 
  selector:
    app: wp 
    name: wpapp-po
  ports:
  - port: 80 
    targetPort: 80

